### ISSUE TITLE
Seems like not working...

### ISSUE THREAD

**Issue by pbt39ppc** [getgrav/grav-plugin-sitemap#33] opened 2017-03-30 03:35 UTC
after installing, on the onelang non en site i see:
http://mysite.name/sitemap
---------------
This page contains the following errors:
error on line 1 at column 8: XML declaration allowed only at the start of the document
Below is a rendering of the page up to the first error.
---------------
and there is nothing below...

**Comment by pbt39ppc** [comment] 2017-03-30 03:42
removing 1st line in the sitemap.xml.twig
<?xml version="1.0" encoding="UTF-8"?>

fixed the issue (but i thing that is too rough), google fing no errors in the sitemap.

**Comment by flaviocopes** [comment] 2017-03-31 10:54
Do you have an empty line at the beginning of the sitemap?

**Comment by pbt39ppc** [comment] 2017-04-04 22:10
now, yes.
but without that empty linw works too.

`
<?xml-stylesheet type="text/xsl" href="{{ uri.rootUrl }}/user/plugins/sitemap/sitemap.xsl"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    {% for entry in sitemap %}
    <url>
        <loc>{{ entry.location|e }}</loc>
        <lastmod>{{ entry.lastmod }}</lastmod>
        {% if entry.changefreq %}
        <changefreq>{{ entry.changefreq }}</changefreq>
        {% endif %}
        {% if entry.priority %}
        <priority>{{ entry.priority|number_format(1) }}</priority>
        {% endif %}
    </url>
    {% endfor %}
</urlset>
`

**Comment by pjfry84** [comment] 2017-04-05 09:49
Hi I got the same error ... after deleting the first line of sitemap.xml.twig (with and without a blanc line) everything works fine now ....

**Comment by rhukster** [comment] 2017-04-05 12:12
Where is this file coming from that has the blank line? The one in the plugin has no blank line. https://github.com/getgrav/grav-plugin-sitemap/blob/develop/templates/sitemap.xml.twig

**Comment by pbt39ppc** [comment] 2017-04-05 12:41
This is workaround.
1) delete all in the first line, the line itself still there, so  it's blank.
or
2) delete all line, so the 2nd line became 1st.

**Comment by pjfry84** [comment] 2017-04-05 12:42
Yes I agree with pbt39ppc ... both solution are working. This is what I meant by saying:

**Comment by flaviocopes** [comment] 2017-04-05 14:40
Can one of you send me (also privately on Slack) your `user/` folder to test? Because I cannot get that white space to show up in the first line.

**Comment by flaviocopes** [comment] 2017-04-05 15:01
@pbt39ppc sent me the site to check. The problem was caused by the (custom) theme having two white spaces after the closing PHP tag. Those 2 spaces appeared before the twig template rendering, so they caused the issue.

**Closed by flaviocopes** 2017-04-05 15:01 UTC
